[project]
name = "whatsapp-analysis"
version = "0.1.0"
description = "An aid for visualizing data in txt chat files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "plotly-express>=0.4.1",
]
